# Generated by Django 4.2.3 on 2023-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
